#-----------------------------------------------------------------------
APP         :=ChatRoomApp
TARGET      :=ChatRoomClient
CONFIG      :=
STRIP_FLAG  := N

INCLUDE     += -I/home/zhengdongqi/app/ChatRoomApp/ChatRoomServer/
LIB         +=
#-----------------------------------------------------------------------
include /usr/local/tars/cpp/makefile/makefile.tars
#-----------------------------------------------------------------------
